### ISSUE TITLE
User can delete an entry

### ISSUE THREAD

**Issue by Sean-Hughes-1** [Sean-Hughes-1/code-journal#2]
Feature
User can delete an entry.

Issue Template
Open a new Issue on your GitHub repository with the title User can delete an entry and paste the following block of [Markdown](https://guides.github.com/features/mastering-markdown/) into the comment box.

## 💰 Motivation

If a user decides that they no longer wish to keep an entry, they should be able to delete it.

## 📐 Plan

Allow users to delete an entry from its edit screen.

## 🖼️ Wireframes

![user can delete an entry mobile](https://lfz-static.s3-us-west-1.amazonaws.com/graphics/wireframes/code-journal/figma/user-can-delete-an-entry-mobile.png)
![user can delete an entry desktop](https://lfz-static.s3-us-west-1.amazonaws.com/graphics/wireframes/code-journal/figma/user-can-delete-an-entry-desktop.png)

## ✅ Task List
- [ ] Add a button to the entry form with the text **Delete Entry** which is only visible when an entry is currently being edited.
- [ ] Show a confirmation modal when the user clicks **Delete Entry**
- [ ] When the user clicks **Cancel**, hide the modal.
- [ ] When the user clicks **Confirm**:
  - [ ] remove the corresponding entry object from the data model's entry array.
  - [ ] remove the entry's `li` element from the DOM.
  - [ ] conditionally uses the `toggleNoEntries` function to show the no entries text if needed.
  - [ ] hide the modal.
  - [ ] swap to the Entries view.
- [ ] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [ ] Test all functionality again in a private browsing session.
- [ ] Fix all errors.
